<li>
    <?php echo $red->rIme . ' ' . $red->rPrezime ?> 
    &lt;<?php echo $red->email ?>&gt;
        <a href="/rezervacija/promjena?ID_rezervacija=<?php echo $red->ID_rezervacija ?>"><i title="Promjeni" class="fas fa-edit"></i></a> 
        <a onclick="return confirm('Sigurno obrisati <?php echo $red->rIme . ' ' . $red->rPrezime ?> ');"
        href="/rezervacija/obrisi?ID_rezervacija=<?php echo $red->ID_rezervacija ?>"><i title="Obriši" class="fas fa-trash" style="color: red;"></i></a>
</li>