<div class="large-4 cell" style="text-align: center;">
    <div class="callout">
        <h1><?php echo $red->gIme ?>
        <br /> <?php echo $red->gPrezime ?></h1>
        <hr />
        <a href="/gost/promjena?ID_gost=<?php echo $red->ID_gost ?>"><i title="Promjeni" class="fas fa-edit fa-2x"></i></a> 
        <a onclick="return confirm('Sigurno obrisati <?php echo $red->gIme . ' ' . $red->gPrezime ?> ');"
         href="/gost/obrisi?ID_gost=<?php echo $red->ID_gost ?>"><i title="Obriši" class="fas fa-trash fa-2x" style="color: red;"></i></a>
    </div>
</div>