<div class="grid-x grid-margin-x">
    <div class="large-8 cell">
        <form action="/gost/trazi" method="get">
            <input type="text" name="uvjet" 
            id="uvjet"
            placeholder="Unesi dio imena ili prezimena"
            value="<?php echo $uvjet ?>">
        </form>
    </div>
    <div class="large-4 cell">
        <a class="success button expanded" 
            href="/gost/novi"
            style="border: 0px;">
            Dodaj novog gosta</a>
    </div>
</div>
<div class="grid-x grid-margin-x">
    <?php 
        foreach($podaci as $red){
            include 'gridStavka.phtml';
        }
        ?>
</div>