<!-- Početak izbornik -->
<div class="title-bar" data-responsive-toggle="example-animated-menu" data-hide-for="medium">
<button class="menu-icon" type="button" data-toggle></button>
<div class="title-bar-title"><?php echo APP::config('nazivAPP'); ?></div>
</div>
<div class="top-bar" id="example-animated-menu" data-animate="hinge-in-from-top spin-out">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text show-for-large">
            <?php echo APP::config('nazivAPP'); ?>
            </li>
            <li><a href="/">Početna</a></li>
            
            <?php if(isset($_SESSION['operater'])):?>
                <li><a href="/nadzornaploca/index">Nadzorna ploča</a></li>
                <li>
                    <a href="#">Details</a>
                    <ul class="vertical menu">
                        <li><a href="/hotel/index">Hotel</a></li>
                        <li><a href="/zaposlenik/index">Zaposlenik</a></li>
                        <li><a href="/rezervacija/index">Rezervacije</a></li>
                        <li><a href="/gost/index">Gost</a></li>
                    </ul>
                </li>
                <?php if(isset($_SESSION['operater']) && $_SESSION['operater']->oUloga==='admin'):?>
                    <li><a href="/operater/index">Operateri</a></li>
                <?php endif;?>
            <?php endif;?>
            <?php if(isset($_SESSION['operater']) && $_SESSION['operater']->oUloga!=='admin'):?>
            <?php endif;?>
            <li><a href="/index/era">ERA</a></li>
            
        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
            <li>
            <?php if(!isset($_SESSION['operater'])): ?>
                <li>
                <a href="/index/prijava">Prijava</a>
                </li>
               
            <?php else:?>
                <a href="/index/odjava">Odjavi 
                <?php echo $_SESSION['operater']->oIme . 
                ' ' . $_SESSION['operater']->oPrezime; ?></a>
            <?php endif;?>
            </li>
        </ul>
    </div>
</div>
<!-- Kraj izbornik -->