<div class="large-4 cell" style="text-align: center;">
    <div class="callout">
        <h1><?php echo $red->zIme ?>
        <br /> <?php echo $red->zPrezime ?></h1>
        <h4><?php echo $red->zHotel ?></h4>
        <hr />
        <a href="/zaposlenik/promjena?ID_zaposlenik=<?php echo $red->ID_zaposlenik ?>"><i title="Promjeni" class="fas fa-edit fa-2x"></i></a> 
        <a onclick="return confirm('Sigurno obrisati <?php echo $red->zIme . ' ' . $red->zPrezime ?> ');"
         href="/zaposlenik/obrisi?ID_zaposlenik=<?php echo $red->ID_zaposlenik ?>"><i title="Obriši" class="fas fa-trash fa-2x" style="color: red;"></i></a>
    </div>
</div>