<div class="large-4 cell" style="text-align: center;">
    <div class="callout">
        <h1><?php echo $red->oIme ?>
        <br /> <?php echo $red->oPrezime ?></h1>
        <?php echo $red->oEmail ?>
        <hr />
        <a href="/operater/promjena?ID_operater=<?php echo $red->ID_operater ?>"><i title="Promjeni" class="fas fa-edit fa-2x"></i></a> 
        <a onclick="return confirm('Sigurno obrisati <?php echo $red->oIme . ' ' . $red->oPrezime ?> ');"
         href="/operater/obrisi?ID_operater=<?php echo $red->ID_operater ?>"><i title="Obriši" class="fas fa-trash fa-2x" style="color: red;"></i></a>
    </div>
</div>