<form class="log-in-form" method="POST"
action="/index/autorizacija">
 <label>Email
    <input type="email" id="email" name="email" value="<?php echo $email ?>">
  </label>
  <label>Password
    <input type="password" id="lozinka" name="lozinka">
  </label>
  <p><input type="submit" class="button expanded" value="Log in"></input></p>
  <hr>

</form>
<?php echo $poruka; ?>
<br>
Email: lukavuk@royalhotels.hr  
  <br>
Sifra: 123456